/// Flutter icons Echair
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Echair
///      fonts:
///       - asset: fonts/Echair.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Echair {
  Echair._();

  static const _kFontFam = 'Echair';
  static const String? _kFontPkg = null;

  static const IconData positionmarker = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
